apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: oauth2.googleapis.com
        - host: login.microsoftonline.com
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: false
  envFrom:
    - secret: omsorgspenger-midlertidig-alene-api.apigw-apikey
    - secret: omsorgspenger-midlertidig-alene-api.sts-credentials
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
