name: Deploy Redis prod-gcp
on:
  push: # Deploys automatically to prod-gcp if there is a change in redis file.
    paths:
      - "redis-config.yml"
    branches:
      - 'master'

jobs:
  deploy-redis-prod-gcp:
    name: Deploy redis to prod-gcp
    if: startsWith(github.ref, 'refs/heads/master') # Deploy if branch is master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Deploy redis to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: "redis-config.yml" 