name: Create/Update Kafka Topics Prod

on:
  push:
    branches:
      - 'master'
    paths:
      - 'nais/topics.yml'

jobs:
  deploy-kafka-topics-prod:
    name: Deploy to Aiven Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          VAR: kafka-pool=nav-prod
          RESOURCE: nais/topics.yml